services:
  php:
    image: phpswoole/swoole:php8.4-alpine
    working_dir: /app
    command: php server.php
    ports:
      - "8088:8080"
    volumes:
      - .:/app

  mariadb:
    image: mariadb:11.7.2
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: bench
      MARIADB_ROOT_PASSWORD: 123456